ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include

obj-$(CONFIG_MTK_N2DM) := n2dm.o
n2dm-objs := n2dm_common.o n2dm_acc.o
