ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
obj-$(CONFIG_MTK_STK8BAXX)	+=  stk8baxx.o
CFLAGS_STK8BAXX.o += -DDEBUG
