ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
#ccflags-y += -w

obj-$(CONFIG_MTK_MC3410_I2C)	:=  mc3410-i2c.o

